### ISSUE TITLE
Next Aired Bugs

### ISSUE THREAD

**Issue by Blurayx** [marcelveldt/script.skin.helper.service#102] opened 2017-09-09 13:04 UTC
Hi marcelveldt,

Please ignore the auto exit I posted earlier. 

There are a few bugs that are more important because I keep missing tv shows.  I'm going to submit the bugs one at a time.

Bug: TV Shows missing from guide

http://thetvdb.com/?tab=season&seriesid=101501&seasonid=708207&lid=7

Ancient Aliens missing from TV Guide. This is an example but there are much more that are missing from the tv guide
Next Aired 7.0.1
[img]https://i.imgur.com/PKKrIHd.png[/img]

Next Aired 6.0.15
I know the days show up different but Ancient Aliens should still show up in V7.0.1(yesterdays column)

[img]https://i.imgur.com/hIcF5rS.png[/img]

**Comment by marcelveldt** [comment] 2017-09-10 17:36
Can you please grab your Kodi log after opening the Nextaired screen ?
I want to make sure there are no errors reported

**Comment by marcelveldt** [comment] 2017-09-10 19:24
hmm, nevermind. I think I've spotted the cause of the issue. Will be fixed in update of tvdb module, available on my repo later today. Mind that it will reset the cache so it will load a bit slow the first time after updating.

**Comment by Blurayx** [comment] 2017-09-10 22:45
I'll report back after testing 
For the other bugs would you like me to creat a new issue?
Hopefully this fix will sort out the other issues I'm having.

Thank you

**Comment by marcelveldt** [comment] 2017-09-11 06:36
Thanks for testing. If you find any new bugs, please create an issue for each bug/question

**Comment by Blurayx** [comment] 2017-09-11 20:01
Hi marcelveldt,

Has the tvdb module been updated yet 

Thanks

**Comment by marcelveldt** [comment] 2017-09-13 19:01
yes it has

**Comment by Blurayx** [comment] 2017-09-13 20:14
Ok, I was expecting to see a date change on the tvdb module, That's why I asked.


Thanks

**Comment by Blurayx** [comment] 2017-09-13 22:30
Update:

There's a slight improvement but some tv shows are still missing.
 
Growing up supermodel missing in 7.x.

6.0.15
<a href="https://imgur.com/varuk0y"><img src="https://i.imgur.com/varuk0y.png" title="source: imgur.com" /></a>

https://www.thetvdb.com/?tab=series&id=333454&lid=7

**Closed as completed** 2021-02-03 21:13 UTC
