### ISSUE TITLE
cannot import name TheTvDb

### ISSUE THREAD

**Issue by hobbypunk90** [marcelveldt/script.skin.helper.service#73] opened 2016-12-13 20:54 UTC
Hello,

i'm not sure if i'm at the correct plugin, but i get this error  😕
i hope you can help.
```
21:37:45.753 T:1662387088   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name TheTvDb
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/script.skin.helper.service/plugin.py", line 10, in <module>
                                                from resources.lib.plugin_content import PluginContent
                                              File "/home/kodi/.kodi/addons/script.skin.helper.service/resources/lib/plugin_content.py", line 17, in <module>
                                                from artutils import KodiDb, Tmdb, get_clean_image, process_method_on_list
                                              File "/home/kodi/.kodi/addons/script.module.skin.helper.artutils/lib/artutils.py", line 28, in <module>
                                                from thetvdb import TheTvDb
                                            ImportError: cannot import name TheTvDb
                                            -->End of Python script error report<--
21:37:45.999 T:1333785488   ERROR: GetDirectory - Error getting plugin://script.skin.helper.service/?action=nextepisodes&limit=25&reload=
```

Greets,
Marcel

**Comment by mgonzales71** [comment] 2016-12-18 07:31
ok to close - duplicate of https://github.com/marcelveldt/script.skin.helper.widgets/issues/3

**Closed as completed** 2016-12-18 07:46 UTC
